name: "setup"
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v27
    - run: nix --version
      shell: bash
    - run: nix config show
      shell: bash
    - uses: ./.github/actions/build_nix
      with:
        # drv: .#p.nixVersions.nix_2_25
        # drv: .#d.nix
        drv: .#less-download-flakes.nixwrapper
        install: "true"
    - run: nix --version
      shell: bash
    - run: nix config show
      shell: bash
