name: "setup"

inputs:
  cachix:
    default: "false"
  CACHIX_AUTH_TOKEN:
    required: false

runs:
  using: "composite"
  steps:
    # https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
    - run: rm -rf /opt/hostedtoolcache
      shell: bash
    - uses: cachix/install-nix-action@v27
    - run: nix --version
      shell: bash
    - run: nix config show
      shell: bash
    - run: nix profile install .#p.cachix
      shell: bash
    - uses: ./.github/actions/build_nix
      with:
        # drv: .#p.nixVersions.nix_2_25
        # drv: .#d.nix
        drv: .#less-download-flakes.nixwrapper
        cachix: ${{ inputs.cachix }}
        CACHIX_AUTH_TOKEN: ${{ inputs.CACHIX_AUTH_TOKEN }}
        install: "true"
    - run: nix --version
      shell: bash
    - run: nix config show
      shell: bash
