# https://docs.docker.com/engine/security/rootless/
# ~/.config/systemd/user/docker.service.d/override.conf
[Service]
# Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_NET=slirp4netns"
# Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=slirp4netns"
Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_DISABLE_HOST_LOOPBACK=false"

# https://stackoverflow.com/questions/72500740/how-to-access-localhost-on-rootless-docker
# Rootless Docker v26.0 now allows you to disable host-loopback-isolation via an EV.
# DOCKERD_ROOTLESS_ROOTLESSKIT_DISABLE_HOST_LOOPBACK=false.
# The EV must be set when the rootless docker service starts.
# It will enable container-to-host communication via the 10.0.2.2 address.


# [25/6] no improvement over slirp4netns
# measured using iperf3, with default DOCKERD_ROOTLESS_ROOTLESSKIT
# Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_NET=pasta"
# Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=implicit"

# [25/6] no improvement over default
# Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_MTU=65520"
