name: CI

on:
  push:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

  nix:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - if: success() || failure()
        run: nix path-info --derivation .#ci-instantiate --option eval-cache false
      - if: success() || failure()
        run: nix run .#p.nixVersions.nix_2_23 -- path-info --derivation .#ci-instantiate --option eval-cache false
      - if: success() || failure()
        run: nix run .#p.nixVersions.nix_2_24 -- path-info --derivation .#ci-instantiate --option eval-cache false
      - if: success() || failure()
        run: nix run .#p.nixVersions.nix_2_25 -- path-info --derivation .#ci-instantiate --option eval-cache false
      - if: success() || failure()
        run: nix shell .#nixwrapper -c nix path-info --derivation .#ci-instantiate --option eval-cache false

      # registery
      - if: success() || failure()
        run: nix path-info --derivation n#emacs
      - if: success() || failure()
        run: nix path-info --derivation p#ci-instantiate

      - if: success() || failure()
        run: nix build .#profile

      - if: success() || failure()
        run: nix path-info --derivation .#less-build.ci-instantiate
      - if: success() || failure()
        run: nix path-info --derivation .#less-download-flakes.ci-instantiate
      - if: success() || failure()
        run: nix path-info --derivation .#less-build.less-download-flakes.ci-instantiate
      - if: success() || failure()
        run: nix path-info --derivation .#emacs29-gtk3.ci-instantiate
      - if: success() || failure()
        run: nix path-info --derivation .#py310.ci-instantiate

      # python
      - if: success() || failure()
        uses: ./.github/actions/build_nix
        with:
          drv: .#python-all
      # test "inject"
      - if: success() || failure()
        run: nix build .#python.inject.pygit2.regexfactory

      - if: success() || failure()
        uses: ./.github/actions/build_nix
        with:
          drv: .#js

  emacs:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs:
          [".#emacs", ".#p.emacs30-nox", ".#p.emacs29-gtk3", ".#p.emacs28-gtk3"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: nix path-info --derivation ${{ matrix.emacs }}
      - if: matrix.emacs == '.#emacs'
        uses: ./.github/actions/build_nix
        with:
          drv: ${{ matrix.emacs }}
      - run: nix profile install ${{ matrix.emacs }}
      # for vterm
      - run: nix profile install .#p.cmake .#p.gnumake .#p.gcc .#p.libtool
      # for lilypond-mode
      - run: nix profile install .#p.lilypond
      - run: mv emacs/alan-private.example.el emacs/alan-private.el
      - if: success() || failure()
        run: emacs --batch --eval "(setq ci-build-verbose t)" -l emacs/ci.el --eval "(ci-show-build-errs)"
      - if: success() || failure()
        run: emacs --batch -l emacs/ci.el --eval "(ci-load-packages)"
      - if: success() || failure()
        run: emacs --batch -l emacs/ci.el --eval "(ci-byte-compile)"
